---
name: Erika Rasnick Manning
position: "Senior Biostatistician/Epidemiologist"
address: ""
phone: 765-256-0925
email: "Erika.Rasnick@cchmc.org"
github: erikarasnick
aboutme: "Experienced Biostatistician and Epidemiologist with a strong foundation in statistical modeling, spatial analysis, and reproducible research workflows. At Cincinnati Children's Hospital, I lead data-driven investigations into environmental and social determinants of health using R (tidyverse, GIS packages, Quarto, Shiny), custom R package development, and computational tools like Git, Docker, and high performance computing environments. My work has contributed to over two dozen peer-reviewed publications, with a focus on advancing population health through rigorous, scalable methods for integrating geospatial and clinical data."
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(glue)
```

```{r, get_data}
library(tidyverse)
library(bib2df)

edu <- read_csv("data/education.csv")

exp <- read_csv("data/experience.csv")

# pubs <- read_csv("data/publications.csv")

pres <- read_csv("data/presentations.csv")

skills <- read_csv("data/skills.csv")
```

# Experience

```{r exp}
exp %>%
  detailed_entries(
    what = role,
    when = glue("{start_date}--{end_date}"),
    with = company,
    where = location
  )
```

# Education

```{r edu}
detailed_entries(
  edu,
  when = glue("{start_date}--{end_date}"),
  what = degree,
  where = location,
  with = university
)
```

# Publications

```{r pubs}
bibliography_entries("data/works.bib")
```

# Presentations

```{r pres}
pres %>%
  filter(!is.na(title)) %>%
  detailed_entries(
    what = event,
    when = date,
    with = title,
    where = location
  )
```

```{r}
# skills %>%
#   detailed_entries(with = skill, why = details)
```


